FROM alpine AS build

RUN apk add --update alpine-sdk boost-dev cmake asio-dev 

ADD ./ /turbopilot/

RUN mkdir /turbopilot/build

WORKDIR  /turbopilot/build

RUN cmake -D GGML_STATIC=ON ..
RUN make turbopilot

FROM alpine AS runtime


WORKDIR /app

COPY --from=build /turbopilot/build/bin/turbopilot /app/turbopilot

ENV THREADS=4

ENV MODEL="/models/codegen-2B-multi-ggml-4bit-quant.bin"

ENV BATCHSIZE=8

COPY ./run.sh /app/

EXPOSE 18080

CMD /app/run.sh